import express from "express";
import { getdata,landingpage,register,login,home,renderlogin,renderrigister,logout,checkpoint } from "../controller/appcontroller.js";
import asyncHandler from "../middleware/asynchandler.js";
import isAuthenticated from "../middleware/auth.js";
const router=express.Router();
router.get('/',asyncHandler(landingpage));
router.get('/session',asyncHandler(checkpoint));
router.get('/login',asyncHandler(renderlogin));
router.get('/register',asyncHandler(renderrigister));
router.post('/login',asyncHandler(login));
router.post('/register',asyncHandler(register));
router.get('/API',isAuthenticated,asyncHandler(getdata));
router.get('/home',isAuthenticated,asyncHandler(home));
router.get('/logout',isAuthenticated,asyncHandler(logout));
export default router;